### ISSUE TITLE
STS 4.17.1 version is not showing the Thymeleaf Suggestion

### ISSUE THREAD

**Issue by modhudeb** [thymeleaf/thymeleaf-extras-eclipse-plugin#118]
how can i solve this?

**Comment by ultraq** [comment]
This plugin was made for the Eclipse WebTools HTML Editor, which hasn't been the default HTML editor in the Spring Tool Suite for quite some time (I'm not even sure if it's packaged w/ STS any more). I've updated the note in the readme so that this is hopefully clearer, including a note to check what editor is being used in HTML files.
