### ISSUE TITLE
not getting code assistance

### ISSUE THREAD

**Issue by rohanmahanti64** [thymeleaf/thymeleaf-extras-eclipse-plugin#131]
After installing thymeleaf in my STS ide I am not getting the code assistance.

**Comment by danthe1st** [comment]
Is the Thymeleaf nature enabled (Right-click on the project>`Configure`>`Add Thymeleaf Nature` or Right click on the project>`Thymeleaf`>`Add Thymeleaf Nature`)?

If that doesn't work, make sure your `eclipse.ini` includes `--add-opens=java.base/java.lang=ALL-UNNAMED` in the JVM arguments (see https://github.com/thymeleaf/thymeleaf-extras-eclipse-plugin/issues/108#issuecomment-1030641320)

**Comment by ultraq** [comment]
This plugin was made for the Eclipse WebTools HTML Editor, which hasn't been the default HTML editor in the Spring Tool Suite for quite some time (I'm not even sure if it's packaged w/ STS any more).  I've updated the note in the readme so that this is hopefully clearer, including a note to check what editor is being used in HTML files.
