### ISSUE TITLE
NO THYMELEAF SUGGETION  

### ISSUE THREAD

**Issue by khushxal** [thymeleaf/thymeleaf-extras-eclipse-plugin#133]
**No content suggestion is coming i.e th: no suggestion. tried everything in sts and updation but not working** This feels very annoying i am using sts and bootproject

**Comment by ultraq** [comment]
This plugin was made for the Eclipse WebTools HTML Editor, which hasn't been the default HTML editor in the Spring Tool Suite for quite some time (I'm not even sure if it's packaged w/ STS any more).  I've updated the note in the readme so that this is hopefully clearer, including a note to check what editor is being used in HTML files.
