### ISSUE TITLE
Processor's restrictions are not working as expected

### ISSUE THREAD

**Issue by tduchateau** [thymeleaf/thymeleaf-extras-eclipse-plugin#16]
Still for Dandelion-DataTables, I'm trying to set some restrictions in the dialect XML file.

```
<?xml version="1.0" encoding="UTF-8"?>
<dialect xmlns="http://www.thymeleaf.org/extras/dialect" 
prefix="dt" namespace-uri="http://www.thymeleaf.org/dandelion/datatables"
class="com.github.dandelion.datatables.thymeleaf.dialect.DataTablesDialect">

   <attribute-processor name="autowidth" class="com.github.dandelion.datatables.thymeleaf.processor.basic.TableAutoWidthAttrProcessor">
        <restrictions tags="table" values="true,false"/>
    </attribute-processor>

</dialect>
```

The processor's rules are :
- must only apply on a table tag.
- the possible values are only "true" or "false".

But in the content assist, the processor is proposed on all HTML tags and I don't see any possible values (true or false).

Did I miss something?

**Comment by ultraq** [comment]
The only thing that sticks out is the `values` attribute is an XML list of strings, and XML lists are whitespace-separated, so you should change the comma into a space.  However, that should only affect what gets proposed when you invoke content assist within the value of your `dt:autowidth` processor :|  I'll run a quick test to see if I get the same behaviour.

**Comment by ultraq** [comment]
I couldn't reproduce it :(  I tried making the `th:inline` processor appear only on `table` elements, then changed its list of values to be comma-separated instead, but then it worked as expected (being proposed only on `table` elements, then it tried to propose "text,javascript,dart" as a single value).

Is the dialect XML file in that other Maven project in your workspace that you mentioned in the other issue you raised?  I'm wondering if maybe the plugin is not reading your newer dialect above because it's resolved using m2e, and is only reading an older one in a project JAR which doesn't have any restrictions on it.

**Comment by tduchateau** [comment]
The conflict is not impossible... :-)
I'll try with a clean workspace and keep you posted!

**Comment by tduchateau** [comment]
I just ran more tests. Actually, it works perfectly :-)

Here are some notes :
- using m2e, since the dependencies mechanism use JARs located in the local Maven repository, whenever you update the XML file of a custom dialect, you have to install the new version of the project containing the XML file in the local repository (mvn install) and re-launch Eclipse to see the changes (maybe there's a easier way? :-))
- not using m2e, the XML file is not scanned at all :-(

**Comment by ultraq** [comment]
Seems to me (from this and the other issue you raised) that I have some m2e integration and 'other project' dependency issues to work out.  I'll track them against that other issue since this one is more about the `<restrictions>` and whether they're working correctly.
