### ISSUE TITLE
Allow default, global configuration for autocompletion on all .html files

### ISSUE THREAD

**Issue by phillipuniverse** [thymeleaf/thymeleaf-extras-eclipse-plugin#20]
First of all, thanks for the awesome work on this plugin! Preliminary testing has this looking pretty good.

Over at [Broadleaf](http://www.broadleafcommerce.org) we use Thymeleaf heavily in our project. However, we have our Thymeleaf templates split out into loads of various partials and then sew them together with th:substitueby. Arguably, this is how most Thymeleaf projects should operate so that you can have separation of concerns as well as remove code duplication in some cases.

If I'm using the current plugin the current way it is designed, then that means that I need to go and add an `xmlns` to all of my template files. In some of the cases with partials, there isn't even a root element defined (the template is just a collection of sibling HTML elements) so I would also have to add the `xmlns` to all of those sibling HTML elements as well.

To be a little more explicit, if I have a Thymeleaf template that looks like this (sorry that this is mostly a contrived example):

``` xml
<div class="container">
    <input th:value="${aModelVariable}"
           class="listgrid-criteria-input datepicker"
           type="text"
           placeholder="Start Date"/>
    <i class="icon-calendar"></i>
</div>
<br />
<div class="datepicker-container">
    <input th:value="${bModelVariable}"
           class="listgrid-criteria-input datepicker"
           type="text"
           placeholder="End Date"/>
    <i class="icon-calendar"></i>
</div>
```

This is then included in a parent template with a `th:substituteby`. Then in order to get the benefits of the Eclipse plugin, I would have to change the above to:

``` xml
<div xmlns:th="http://www.thymeleaf.org" class="container">
    <input th:value="${aModelVariable}"
           class="listgrid-criteria-input datepicker"
           type="date"
           placeholder="Start Date"/>
    <i class="icon-calendar"></i>
</div>
<br />
<div xmlns:th="http://www.thymeleaf.org" class="datepicker-container">
    <input th:value="${bModelVariable}"
           class="listgrid-criteria-input datepicker"
           type="date"
           placeholder="End Date"/>
    <i class="icon-calendar"></i>
</div>
```

This is really more of an enhancement request, and I'm curious if this is how others are using Thymeleaf in their projects. For us, all of our template files are in Thymeleaf, so it would be nice if there is some sort of global configuration for 'Give content assist to all of the following file suffixes'.

I would love to help contribute but my knowledge of Eclipse plugins is slim to none. I will attempt to come up with something towards this goal but wanted to get this on paper publicly rather than let it just sit in my head :)

Again, thanks for all the hard work!

**Comment by ultraq** [comment]
Ah, of course - template fragments (I always forget about those)!  I haven't had the need to split templates in my own projects into such small pieces, so have always dealt with full pages that have the HTML root element where I can put the namespace.  Thus, the Eclipse plugin was initially made to support that way of working.

I also made the `xmlns` part a requirement so that the plugin would then know to add Thymeleaf suggestions to it.  I didn't want to start 'poisoning' all of your HTML files with Thymeleaf suggestions when the developer didn't ask for them.

But in your case, I can understand how this becomes a bit of a problem.  Having to add that extra `xmlns` information is just boilerplate code that can become a pain.  You _could_ add wrap your templates in a common HTML tag that has the namespace, but that's just adding boilerplate code again when such a thing could be inferred if there was the ability to do just as you suggested - to say "Hey, this is a Thymeleaf project.  I want Thymeleaf suggestions _everywhere!!!!11_" :)

I had been thinking about ways to mark a project as a Thymeleaf one so I could fulfil other feature requests like #9, and some solutions that came to mind were to create a Thymeleaf project 'nature' (much like how you mark Eclipse projects as being Java, or Groovy, or Java web app, to have Maven manage dependencies, etc), or a Thymeleaf project 'facet' (this is just for Java web apps, and is part of the Eclipse WTP plugin).  I haven't decided which way to go for that, but when I do, I'll be sure to make it so that if a project has that nature/facet, then it's implied that all HTML files are Thymeleaf template files and the plugin can safely make Thymeleaf suggestions in the HTML files, even without the `xmlns:th` part.  This could even extend to any dialect dependencies found in the project.

**Comment by phillipuniverse** [comment]
Did a bit more digging and I think you're right; having a Thymeleaf Facet is probably the way to go. Looks like you can also provide content assist by associating a custom editor as well but I don't think that's the best solution.

**Comment by ultraq** [comment]
Done, using a new Thymeleaf nature that can be applied to a project.
