### ISSUE TITLE
Content Assist Doesn't appear to be working

### ISSUE THREAD

**Issue by phillipuniverse** [thymeleaf/thymeleaf-extras-eclipse-plugin#25]
What I did:
1. Cloned the repo
2. Switched to the 2.0-dev branch
3. Executed a mvn install on the repo that I cloned
4. Went to Help -> Install New Software
5. Added the path to the update-site folder on my filesystem
   ![screen shot 2013-06-13 at 12 01 07 pm](https://f.cloud.github.com/assets/684275/649714/e816e4d2-d44a-11e2-8949-e3b895eee8e8.png)
6. Completed the plugin install
7. Restarted Eclipse

My Eclipse about screen (Juno SR2)
![screen shot 2013-06-13 at 12 09 52 pm](https://f.cloud.github.com/assets/684275/649769/1ca7c440-d44c-11e2-9297-c6328fd0a986.png)

And showing the Thymeleaf install in the about -> installation details:
![screen shot 2013-06-13 at 12 10 35 pm](https://f.cloud.github.com/assets/684275/649773/30828ae0-d44c-11e2-8beb-a1d07c93b47a.png)

Looks like the install worked, because I was able to see the Thymeleaf nature option on my project: 
![screen shot 2013-06-13 at 12 02 46 pm](https://f.cloud.github.com/assets/684275/649723/1afea754-d44b-11e2-80d1-a5da5de99ba8.png)

After I added it though, I do not get any content assist for the Thymeleaf standard dialect and my HTML files have warnings about not being able to find th:
![screen shot 2013-06-13 at 12 04 12 pm](https://f.cloud.github.com/assets/684275/649732/4ea1ec9c-d44b-11e2-9840-c0133841aec0.png)

![screen shot 2013-06-13 at 12 04 57 pm](https://f.cloud.github.com/assets/684275/649739/6a482132-d44b-11e2-86bc-3f88e3ffe902.png)

If I add the th: namespace to a root node, warnings go away but no content-assist:
![screen shot 2013-06-13 at 12 08 15 pm](https://f.cloud.github.com/assets/684275/649758/e0c577d8-d44b-11e2-95ac-062a2bfee76d.png)
![screen shot 2013-06-13 at 12 08 54 pm](https://f.cloud.github.com/assets/684275/649761/f3f17604-d44b-11e2-8393-1e434fb35776.png)

Maybe I configured something wrong?

**Comment by phillipuniverse** [comment]
I also attempted the same things but installed the plugin via the built .zip file in target rather than using it update-site folder. Same results.

**Comment by ultraq** [comment]
It looks like you've done everything right, but something is missing.

As for the 'cannot find th namespace' warnings, that is normal since the HTML validator is still doing its job and I haven't thought to implement anything that 'undoes' those validation errors, even with the Thymeleaf nature applied.  I'll raise another issue for that to track it and figure out what I can do about that.

**Comment by phillipuniverse** [comment]
Gotcha; makes sense about the validator results.

Let me know if you find anything that I can help test. I wouldn't mind testing this myself as well, but I am unfamiliar with debugging Eclipse plugins. Any suggestions that you do when developing locally? (obviously I can Google and probably find decent results)

**Comment by ultraq** [comment]
So I found a bunch of NullPointerExceptions happening when I tested this again using a brand new test workspace (the old workspace worked fine).  I cleared those up and things started working as expected.  (The problem turned out to be that the code expected your project to have project dependencies that contained dialect XML files.  If it didn't have those, then NPEs all the way down.)

Could you check-out the latest code from the 2.0-dev branch, rebuild the plugin, and retest?  I'll wait for your feedback before closing this issue.

As for debugging Eclipse plugins, what I've done is to create a new Eclipse Application launch type in the Debug Configurations screen - it creates a new Eclipse installation and workspace that I can launch from my current Eclipse installation in a debug mode.  Within that configuration screen there's a Plugins tab where I pick what plugins to launch with that new Eclipse, namely the Thymeleaf ones.  (You may also need to add `-XX:MaxPermSize=128m` to the VM Arguments section too, otherwise it runs out of memory way too fast.)  This lets me test Eclipse plugin changes without having to go through the process of building and installing.

**Comment by phillipuniverse** [comment]
Looks like that did it. Pulled down the latest and reinstalled and content assist is looking good:

![screen shot 2013-06-13 at 7 53 47 pm](https://f.cloud.github.com/assets/684275/651994/ee018cde-d48c-11e2-9397-8c599de585f2.png)

Thanks for the info on debugging, I'll hopefully be able to offer a pull request rather than just an issue report for further things I run into. Planning on documenting the custom Broadleaf dialect to conform to the documentation xsd ASAP so I'll be able to provide more feedback and probably suggest/introduce some features as a result of that process.

Again, thanks for the great work!

**Comment by Satyam-kale** [comment]
i have same problem  what ia can do for it
