### ISSUE TITLE
Non-blocking error when scanning help files

### ISSUE THREAD

**Issue by tduchateau** [thymeleaf/thymeleaf-extras-eclipse-plugin#47]
As soon as the content assist is being used, i.e. as soon as help files are scanned, Eclipse throws a non-blocking error:

![image](https://f.cloud.github.com/assets/1398586/2009946/f3cf37a0-8766-11e3-9648-bec7efa29ef3.png)

As the error says, it appears that a `rmi.dtd` file is not present in my Eclipse installation.
Note that it does not prevent the help file from being scanned and loaded.

**Comment by ultraq** [comment]
I noticed I get these too.  Looks like the XML parser is trying to resolve a DTD file.  I should see if I can configure it to remove those kinds of lookups during that phase.

**Comment by ultraq** [comment]
Just tried a bunch of methods to configure the `XPathFactory`, none of them seem to work:
- [this answer from SO](http://stackoverflow.com/questions/5079832/turn-off-dtd-validation-in-xpathexpression-evaluate) is for parsers.  Setting it on the XPathFactory causes configuration exceptions to be thrown
- some new XML constants for accessing external resources are for Java 7 and newer only, so couldn't try those either

Problem seems to be that I can't access the underlying DOM parser that the XPath expression uses under the hood.

Next thing to try: parse the document myself with a SAX parser, listening only for the namespace event (or first element event and check for a namespace) since that's all the original XPath expression is used for.

**Comment by ultraq** [comment]
Yup, the non-resolving SAX parser seemed to fix it.
