### ISSUE TITLE
Missing Update Site?

### ISSUE THREAD

**Issue by pioto** [thymeleaf/thymeleaf-extras-eclipse-plugin#64]
It seems the Eclipse update site now 404s?

http://www.thymeleaf.org/eclipse-plugin-update-site/

**Comment by ultraq** [comment]
We get this (the issue, not 404s) a lot, so please see if the solutions mentioned in these similar issues are of any help: 
- https://github.com/thymeleaf/thymeleaf-extras-eclipse-plugin/issues/59
- https://github.com/thymeleaf/thymeleaf-extras-eclipse-plugin/issues/58

**Comment by dlmiles** [comment]
This is silly, is there a technical reason why it doesn't redirect to (or display itself) "HOWTO update eclipse information" on that page when access from regular browser with a human viewing the content interactively ?

**Comment by ultraq** [comment]
No, nothing's preventing us from doing that (just putting an index.html page in there) - I was thinking of doing something like that seeing as so many devs just head to that site with their browsers instead of Eclipse as per the instructions.  It'll just be a repeat of that section of the readme though.

**Comment by pioto** [comment]
I definitely tried pasting the URL into Eclipse before checking in the
browser, and saw nothing available to install. Fetching the .zip from
SourceForge was the only option that seemed to work. Perhaps there was some
transient issue...

I have no proxy at work, and I believe I was able to install this plugin
successfully via the update site in the past...

**Comment by ultraq** [comment]
I've just added an index.html page so that browser visitors at least see something.  I also just installed the plugin via the update site on a clean install of Eclipse just to make sure that change didn't alter anything, and that seemed to work.

It may be a SourceForge thing as that's where the packages are ultimately hosted.  I guess it's time to start looking for a new home: #65

**Comment by pioto** [comment]
Seems the update site I had configured before now actually shows things... so I guess I hit some transient error... closing this out.
