### ISSUE TITLE
在eclipse的oxygen版本安装失败

### ISSUE THREAD

**Issue by Hydya** [thymeleaf/thymeleaf-extras-eclipse-plugin#82]
我在eclipse中根据网址http://www.thymeleaf.org/eclipse-plugin-update-site/安装thymeleaf插件时报错，信息如下
Unable to read repository at http://www.thymeleaf.org/eclipse-plugin-update-site/content.xml.
Unable to read repository at http://www.thymeleaf.org/eclipse-plugin-update-site/content.xml.
Connection reset
请问是插件仓库改变了吗

**Comment by zql3315** [comment]
同上

**Comment by Hydya** [comment]
如果你有market place  可以直接在上面搜索thymeleaf来安装插件，或者直接在github下载离线的插件包，通过离线的方法安装此插件

**Comment by ultraq** [comment]
I'm sorry, I don't speak Chinese.  However, it looks like you experienced a network issue when trying to install the Eclipse plugin.

As our plugin site is hosted on GitHub pages, which then redirect to Bintray, much of the network issues are out of our control.  We do have a few alternatives to the update site though:

 - you can install the plugin on the Eclipse Marketplace (search for "thymeleaf")
 - you can downloading a ZIP file of the plugin from Bintray: https://bintray.com/thymeleaf/downloads/thymeleaf-extras-eclipse-plugin/2.1.2

Hopefully one of those options will work for you.  Otherwise, trying at another time has also shown to work as downtime for GitHub pages and/or Bintray is usually only temporary.
